### PR TITLE
WITH `BOT_USER_ID`

### PR DESCRIPTION
**Pull request by 0x4007**
Testing pull and deploy against self

### CODE REVIEW

**Comment by 0x4007** [comment]
Status 405 on gets on the new account after a manual deploy.

```json
{
  "truncated": false,
  "outcome": "ok",
  "scriptVersion": {
    "id": "a4f9f001-c6a7-4601-84f9-2e838622beca"
  },
  "scriptName": "ubiquibot-command-start-stop",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [],
  "eventTimestamp": 1726335924888,
  "event": {
    "request": {
      "url": "https://ubiquibot-command-start-stop.6cz7c9w25c.workers.dev//manifest.json",
      "method": "GET",
      "headers": {
        "accept-encoding": "gzip",
        "cf-connecting-ip": "2a06:98c0:3600::103",
        "cf-ipcountry": "US",
        "cf-ray": "8c3230ca830d28c6",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "cf-worker": "ubq.workers.dev",
        "connection": "Keep-Alive",
        "host": "ubiquibot-command-start-stop.6cz7c9w25c.workers.dev",
        "x-forwarded-proto": "https",
        "x-real-ip": "2a06:98c0:3600::103"
      },
      "cf": {
        "longitude": "-97.82200",
        "httpProtocol": "HTTP/1.1",
        "tlsCipher": "",
        "continent": "NA",
        "asn": 36459,
        "country": "US",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsVersion": "",
        "colo": "IAD",
        "timezone": "America/Chicago",
        "verifiedBotCategory": "",
        "edgeRequestKeepAliveStatus": 1,
        "tlsClientRandom": "",
        "tlsClientExtensionsSha1": "",
        "tlsClientHelloLength": "",
        "asOrganization": "GitHub",
        "requestPriority": "",
        "latitude": "37.75100"
      }
    },
    "response": {
      "status": 405
    }
  },
  "id": 0
}
```

**Comment by 0x4007** [comment]
Have to remove slash from the worker endpoint on the config. 

Back to square one 

```
        "Error: Unable to decode value as it does not match the expected schema"
```

**Comment by 0x4007** [comment]
>         "Error: Unable to decode value as it does not match the expected schema"

@gentlementlegen @keyrxng @whilefoo let me know how to fix. I started the night with this six hours ago and ended the night with this.

```yml
plugins:
  - uses:
    - plugin: https://ubiquibot-command-start-stop.0x4007.workers.dev
      with:
        reviewDelayTolerance: "3 Days"
        taskStaleTimeoutDuration: "30 Days"
```

**Comment by gentlementlegen** [comment]
First I think you have a dangling slash that you should remove to avoid accidents, coming from
`"url": "https://ubiquibot-command-start-stop.6cz7c9w25c.workers.dev//manifest.json",`
Two it seems that your worker failed to deploy
https://github.com/0x4007/command-start-stop/actions/runs/10864332788/job/30149480620?pr=2#step:6:66
I suspect your API token from Cloudflare might not have all the permissions necessary.

**Comment by 0x4007** [comment]
Refer to latest comments the url is https://ubiquibot-command-start-stop.0x4007.workers.dev and it deployed fine.  

Well technically I manually deployed but that doesn't answer the question about wrong schema

**Comment by gentlementlegen** [comment]
What branch is deployed?

**Comment by 0x4007** [comment]
It's this pull

**Pull request closed without merging**
